# run: conda env create --file environment.yml
name: face_rec
dependencies:
  - python=3.8
  - numpy=1.21.5
  - face_recognition=1.3.0
  - pip:
    - opencv-python==4.5.5.64
    - pyyaml==6.0
    - fastcore==3.0.8
