# run: conda env create --file environment.yml
name: face_rec
channels:
- conda-forge
- bioconda
- bokeh
- defaults
dependencies:
 - dlib=19.23.1
 - python=3.8
 - numpy=1.21.5
 - pip
 - face_recognition=1.3.0
 - pip:
   - opencv-python==4.5.5.64
