Model:
  enc_model_size: 'large'
  upsample: 0
  model: 'hog'
  num_jitters: 1
  thres: 0.43 # lower == stricter to predict from comparison
  enc_force_load: False
  frame_skip: 12 # should not be more than 30
  frame_resz: 0.8


Encodings:
  enc_list: ''

Predictions:
  max_size: 4
  min_pred: 3